


    english () {
      return [
        "What is your f name?"
      , "My name is"
      , "Excuse f me"
      , "What is your inf name?"
      , "I have..."
      , "Excuse inf me"
      , "You f have..."
      , "You inf have..."
      , "You inf have money "
      , "I have a job"
      , "to speak"
      , "Do you inf have any children?"
      , "to work "
      , "I speak Russian a little bit"
      , "to live"
      , "I work in Moscow"
      , "to have lunch"
      , "I live in Russia"
      , "to get up"
      , "I have lunch at one o'clock"
      , "I get up at six in the morning"
      , "to have breakfast"
      , "to drink"
      , "I have breakfast at home"
      , "I speak with colleagues in English"
      , "I like to drink coffee at work "
      , "I am reading a newspaper"
      , "to read"
      , "I am writing a letter"
      , "to write"
      , "I have lunch at a cafe"
      , "to have lunch"
      , "to play football"
      , "to play "
      , "Today I am having dinner at a restaurant"
      , "to have dinner"
      , "I am having a rest"
      , "to have a rest"
      , "In the evening I watch the news"
      , "to watch"
      , "I listen to music in the car"
      , "to listen"
      , "What does he do at work?"
      , "to do"
      , "It was cold yesterday"
      , "I talk with clients by phone"
      , "It's warm today"
      , "to be"
      , "to cost "
      , "It will be hot tomorrow"
      , "At what time?"
      , "How much does milk cost?"
      , "I buy groceries at a supermarket"
      , "to buy"
      , "to be situated|to be"
      , "Will you inf be in Moscow next week?"
      , "What are you doing now? "
      , "Where is the Bolshoy Theatre?"
      , "Four years ago I was working for a Russian company"
      , "Two years ago I was living in London"
      , "Today I had dinner in a restaurant"
      , "Yesterday I had lunch in a cafe"
      , "Two weeks ago I was in a museum"
      , "Two days ago I was in Amsterdam"
      , "I go to work by car"
      , "to go |(by transport, regularly, in many directions)"
      , "I like to walk"
      , "to go |(on foot, regularly, in many directions)"
      , "I like to go by taxi"
      , "Every week I go to the theatre"
      , "I can"
      , "I must"
      , "I can work a lot"
      , "I must work"
      , "In a month's time I will be working  in Moscow"
      , "In a year's time I will be living in Italy "
      , "to go|(by transport, not regularly, in one direction)"
      , "to go|(on foot, not regularly, in one direction)"
      , "Tomorrow I will go at work by car"
      , "Today I am going to the theatre"
      ]
    }


    russian () {
      return [
        "Меня зовут..."
      , "Как вас зовут?"
      , "Как тебя зовут?"
      , "Извините"
      , "Извини"
      , "У меня есть.."
      , "У тебя есть..."
      , "У вас есть..."
      , "У меня есть работа"
      , "У тебя есть деньги"
      , "У вас есть дети?"
      , "говорить"
      , "Я немного говорю по-русски"
      , "работать"
      , "Я работаю в Москве."
      , "жить"
      , "Я живу в России"
      , "обедать"
      , "Я обедаю в час"
      , "вставать"
      , "завтракать"
      , "Я встаю в шесть утра"
      , "Я завтракаю дома"
      , "пить"
      , "Я люблю пить кофе на работе"
      , "Я говорю с коллегами по-английски"
      , "читать"
      , "Я читаю газету"
      , "писать"
      , "Я пишу письмо"
      , "обедать"
      , "Я обедаю в кафе"
      , "играть"
      , "играть в футбол"
      , "ужинать"
      , "Сегодня я ужинаю в ресторане"
      , "отдыхать"
      , "я отдыхаю"
      , "смотреть"
      , "Вечером я смотрю новости"
      , "слушать"
      , "Я слушаю музыку в машине"
      , "делать"
      , "Что он делает на работе?"
      , "Я говорю по телефону с клиентами"
      , "Вчера было холодно"
      , "быть"
      , "Сегодня тепло"
      , "Завтра будет жарко"
      , "стоить"
      , "Сколько стоит молоко?"
      , "Во сколько?"
      , "покупать"
      , "Я покупаю продукты в супермаркете"
      , "Ты будешь в Москве на следующей неделе?"
      , "находиться"
      , "Где находится Большой театр?"
      , "Что ты сейчас делаешь?"
      , "Два года назад я жил в Лондоне"
      , "Четыре года назад я работал в русской компании"
      , "Вчера я обедал в кафе"
      , "Сегодня я ужинал в ресторане"
      , "Два дня назад я был в Амстердаме"
      , "Две недели назад я был на выставке"
      , "ездить"
      , "Я езжу на работу на машине"
      , "ходить"
      , "Мне нравится ходить пешком"
      , "Каждую неделю я хожу в театр"
      , "Я люблю ездить на такси"
      , "я должен"
      , "я могу"
      , "Я должен работать"
      , "Я могу много работать"
      , "Через год я буду жить в Италии"
      , "Через месяц я буду работать в Москве"
      , "идти"
      , "ехать"
      , "Сегодня я иду в театр"
      , "Завтра я еду на работу на машине"
      ]
    }